site_name: The GeoSPARQL Ontology
site_description: The GeoSPARQL ontology converted into a website
repo_url: https://github.com/ISO-TC204/ontology-import-geo
nav:
- TC204 on ISO.org: https://www.iso.org/committee/54706.html
- TC 204 Home: https://isotc204.org/
- RITSO Home: https://isotc204.org/ritso/
- The GeoSPARQL Ontology:
  - Home: index.md
  - Classes:
    - Feature: classes/Feature.md
    - Feature Collection: classes/FeatureCollection.md
    - Geometry: classes/Geometry.md
    - Geometry Collection: classes/GeometryCollection.md
    - Spatial Object: classes/SpatialObject.md
    - Spatial Object Collection: classes/SpatialObjectCollection.md
  - Properties:
    - asDGGS: properties/asDGGS.md
    - asGeoJSON: properties/asGeoJSON.md
    - asGML: properties/asGML.md
    - asKML: properties/asKML.md
    - asWKT: properties/asWKT.md
    - coordinateDimension: properties/coordinateDimension.md
    - defaultGeometry: properties/defaultGeometry.md
    - dimension: properties/dimension.md
    - ehContains: properties/ehContains.md
    - ehCoveredBy: properties/ehCoveredBy.md
    - ehCovers: properties/ehCovers.md
    - ehDisjoint: properties/ehDisjoint.md
    - ehEquals: properties/ehEquals.md
    - ehInside: properties/ehInside.md
    - ehMeet: properties/ehMeet.md
    - ehOverlap: properties/ehOverlap.md
    - hasArea: properties/hasArea.md
    - hasBoundingBox: properties/hasBoundingBox.md
    - hasCentroid: properties/hasCentroid.md
    - hasDefaultGeometry: properties/hasDefaultGeometry.md
    - hasGeometry: properties/hasGeometry.md
    - hasLength: properties/hasLength.md
    - hasMetricArea: properties/hasMetricArea.md
    - hasMetricLength: properties/hasMetricLength.md
    - hasMetricPerimeterLength: properties/hasMetricPerimeterLength.md
    - hasMetricSize: properties/hasMetricSize.md
    - hasMetricSpatialAccuracy: properties/hasMetricSpatialAccuracy.md
    - hasMetricSpatialResolution: properties/hasMetricSpatialResolution.md
    - hasMetricVolume: properties/hasMetricVolume.md
    - hasPerimeterLength: properties/hasPerimeterLength.md
    - hasSerialization: properties/hasSerialization.md
    - hasSize: properties/hasSize.md
    - hasSpatialAccuracy: properties/hasSpatialAccuracy.md
    - hasSpatialResolution: properties/hasSpatialResolution.md
    - hasVolume: properties/hasVolume.md
    - isEmpty: properties/isEmpty.md
    - isSimple: properties/isSimple.md
    - rcc8dc: properties/rcc8dc.md
    - rcc8ec: properties/rcc8ec.md
    - rcc8eq: properties/rcc8eq.md
    - rcc8ntpp: properties/rcc8ntpp.md
    - rcc8ntppi: properties/rcc8ntppi.md
    - rcc8po: properties/rcc8po.md
    - rcc8tpp: properties/rcc8tpp.md
    - rcc8tppi: properties/rcc8tppi.md
    - sfContains: properties/sfContains.md
    - sfCrosses: properties/sfCrosses.md
    - sfDisjoint: properties/sfDisjoint.md
    - sfEquals: properties/sfEquals.md
    - sfIntersects: properties/sfIntersects.md
    - sfOverlaps: properties/sfOverlaps.md
    - sfTouches: properties/sfTouches.md
    - sfWithin: properties/sfWithin.md
    - spatialDimension: properties/spatialDimension.md
  - Datatypes:
    - dggsLiteral: datatypes/dggsLiteral.md
    - geoJSONLiteral: datatypes/geoJSONLiteral.md
    - gmlLiteral: datatypes/gmlLiteral.md
    - kmlLiteral: datatypes/kmlLiteral.md
    - wktLiteral: datatypes/wktLiteral.md
site_url: https://isotc204.org/ontology-import-geo/
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
  <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank"
  rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"
  alt=""></a></p>
theme:
  name: material
  features:
  - content.code.copy
  - content.status
  - content.tooltips
  - icons
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
- stylesheets/extra.css
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
plugins:
- search
- git-revision-date-localized:
    type: date
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- md_in_html
- meta
- footnotes
- pymdownx.blocks.caption
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: docs
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: ''
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
extra:
  search:
    highlight: true
  hide:
  - title
  version:
    provider: mike
    alias: true
    default: latest
